version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8181:80"
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "e_transparencia"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    networks:
      - default

  # redis
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_dev:/data
    networks:
      - default

networks:
  default:


volumes:
  pg_data_dev:
  redis_dev:
